services:
  socket-server:
    build: .
    container_name: socket-server
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
